version: '3'

services:

  storage:
      image: carcasspg_storage
      expose:
        - "5432"
      ports:
        - "5432:5432"
      networks:
        - netmain
      volumes:
        - var_lib_postgresql_data:/var/lib/postgresql/data
      # .............................................
      restart: always

  mediatry:
      image: carcasspg_mediatry
      tty: true
      expose:
        - "8000"
      ports:
        - "8000:8000"
      networks:
        - netmain
      depends_on:
        - storage
      environment:
        - PROJECT=mediatry      
        - WORKON_HOME=/mediatry/.env         
        - DJANGO_SETTINGS_MODULE=settings.dev        
      volumes:
        - ../../images/mediatry/src:/mediatry
      # .............................................        
      restart: always        
      command: /usr/local/bin/migrate.sh

volumes:
  var_lib_postgresql_data:

networks:
  netmain:
    driver: bridge
   